title: "Buttons"
description: |
  Buttons should be used in situations where a dramatic, obvious action is required. Try not to overuse buttons because they should be the primary call-to-action for a screen.

patterns:
  basic-button:
    title: "Basic"
    description: |
      Default to using the basic button. It should always be used in front of light backgrounds.
    fields:
    - name: nav
      type: string
      example: "Next"
    - name: url
      type: url
      example: "/insert-link/"
  time-btn:
    title: "Time"
    description: |
      This button is used to select the time of an appointment within the calendar.
    fields:
      - name: time
        type: string
        example: "4PM"
      - name: url
        type: url
        example: "/insert-link/"
  back-btn:
    title: "Back"
    description: |
      This icon allows users to nagivate backwards.
    fields:
      - name: url
        type: url
        example: "/insert-link/"
